export const FETCH_DATA_REQUEST = "FETCH_DATA_REQUEST";
export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_DATA_ERROR = "FETCH_DATA_ERROR";

export const EDIT_DATA_ERROR = "EDIT_DATA_ERROR";
export const EDIT_DATA_SUCCESS = "EDIT_DATA_SUCCESS";
